### PR TITLE
Add optional word delimiter argument

### PR DESCRIPTION
**Pull request by ismyrnow**
Not sure if you're interested in this PR, but I had the need for delimiting words strictly on spaces, instead of on non-word characters.

I included extra tests for the previous functionality, and new tests for the new functionality, as well as documentation.

I also bumped the minor version, since this is an API change, but is backwards compatible.

### CODE REVIEW

**Comment by timjrobinson** [comment]
Looks great! Thanks for the PR. 

I think only splitting on spaces should be default, that was the original intention, to be just like split but allow using quotes to group words.

Can you add some tests please, then I will merge.

**Comment by ismyrnow** [comment]
Alright. I undid the version bump and there are both tests and documentation for the new functionality.

**Comment by ismyrnow** [comment]
Just reread your message, and it sounds like you'd rather have that (delimit only on spaces) as the default functionality.

I will make a separate pull request with that, since it's pretty different than what I did. I will remove the optional regex delimiter, since it's technically not functionality I was looking for. It also keeps the module small and simple.

**Comment by ismyrnow** [comment]
Closing this in favor of changing default behavior. See PR #2.

**Pull request closed without merging**
